{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "paths": {
    "/api/v1/orders": {
      "get": {
        "summary": "Get all Users",
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "user_id": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "blog found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "email": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "email"
                  ]
                }
              },
              "application/xml": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "email": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "email"
                  ]
                }
              }
            }
          },
          "404": {
            "description": "blog not found",
            "content": {
            }
          },
          "406": {
            "description": "unsupported accept header",
            "content": {
            }
          }
        }
      }
    },
    "/api/v1/auth/sign_in": {
      "post": {
        "summary": "User SignIn",
        "tags": [
          "User"
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "email created",
            "content": {
            }
          },
          "422": {
            "description": "invalid request",
            "content": {
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "string",
                "properties": {
                  "title": {
                    "email": "string"
                  },
                  "content": {
                    "password": "string"
                  }
                },
                "required": [
                  "email",
                  "password"
                ]
              }
            },
            "application/xml": {
              "schema": {
                "type": "string",
                "properties": {
                  "title": {
                    "email": "string"
                  },
                  "content": {
                    "password": "string"
                  }
                },
                "required": [
                  "email",
                  "password"
                ]
              }
            }
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "localhost:3000"
        }
      }
    }
  ]
}